galaxy_info:
  author: Sebastian Łach
  description: Custom zsh role
  license: MIT
  min_ansible_version: 2.1.2
  platforms:
  - name: ArchLinux
    versions:
    - all
    - any
  galaxy_tags:
    - system
dependencies: []
